=== Fonsi20/Estudios/FRMCode/DAM/1º/LM/XML/1º e 2º/exemplodatosxsd/datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="datos">
<xs:complexType>
<xs:sequence>
<xs:element name="cadena" type="xs:string"/>
<xs:element name="decimal" type="xs:decimal"/>
<xs:element name="entero" type="xs:integer"/>
<xs:element name="boleano" type="xs:boolean"/>
<xs:element name="fecha" type="xs:date"/>
<xs:element name="fechah" type="xs:dateTime"/>
<xs:element name="enteropos" type="xs:positiveInteger"/>
<xs:element name="enteroneg" type="xs:negativeInteger"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Fonsi20/Estudios/FRMCode/XML/exemplodatosxsd/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="datos.xsd">
    <cadena>Hola</cadena>
    <decimal>25.3</decimal>
    <entero>25</entero>
    <boleano>true</boleano>
    <fecha>2018-07-09</fecha>
    <fechah>2018-07-09T23:00:00</fechah>
    <enteropos>36</enteropos>
    <enteroneg>-36</enteroneg>
</datos>
