=== Fonsi20/Estudios/FRMCode/XML/Indicadores/i.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="personas">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellido" type="xs:string"/>
                </xs:all>
            </xs:complexType>
        </xs:element>
        <xs:element name="trabajadores" maxOccurs="unbounded">
            <xs:complexType>
                <xs:choice>
                    <xs:element name="miembros" type="xs:string"/>
                    <xs:element name="empleado" type="xs:string"/>
                </xs:choice>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Fonsi20/Estudios/FRMCode/DAM/1º/LM/XML/1º e 2º/Indicadores/indicadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="i.xsd">
    <persona>
        <nombre>Pepe</nombre>
        <apellido>Vazquez</apellido>
    </persona>
    <persona>
        <apellido>Milla</apellido>
        <nombre>Ana</nombre>
    </persona>
    <trabajadores>
        <miembros>asd</miembros>
    </trabajadores>
    <trabajadores>
        <empleado>asd</empleado>
    </trabajadores>
</personas>
